name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout com histórico completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gerar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: matheuscosta71
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Publicar na branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
